<?php

use PHPUnit\Framework\TestCase;
use jpuck\avhost\Utils\Signature;

class SignatureTest extends TestCase
{
    public function test_can_instantiate_object()
    {
        $this->assertInstanceOf(Signature::class, new Signature);
    }

    public function test_can_get_signature_string()
    {
        $version = getenv('AVHOST_VERSION_NUMBER');

        $datetime = date('c');

        $expected = <<<SIGNATURE
##########################################
# Generated by avhost
# https://github.com/jpuck/avhost
# version $version
# created at $datetime
##########################################
SIGNATURE;

        $actual = (string) new Signature;

        $this->assertSame($expected, $actual);
    }
}
