<?php

namespace jpuck\avhost\Utils;

class Signature
{
    public function __toString()
    {
        $version = (new Version)->getVersion();

        $datetime = date('c');

        return <<<SIGNATURE
##########################################
# Generated by avhost
# https://github.com/jpuck/avhost
# version $version
# created at $datetime
##########################################
SIGNATURE;
    }
}
